title: Settings
fields:
  -
    handle: is_fullpage
    field:
      default: false
      type: toggle
      display: Fullpage
      icon: toggle
      instructions: 'Define if a page is in fullpage mode.'
      localizable: false
      listable: hidden
      instructions_position: above
      visibility: visible
      replicator_preview: true
      hide_display: false
      width: 33
  -
    handle: show_portfolio_filter
    field:
      default: false
      type: toggle
      display: 'Show Portfolio Filter'
      icon: toggle
      localizable: false
      width: 33
      listable: hidden
      instructions_position: above
      visibility: visible
      replicator_preview: true
      hide_display: false
      instructions: 'Define if the portfolio filter is visible.'
  -
    handle: show_team_filter
    field:
      default: false
      type: toggle
      display: 'Show Team Filter'
      icon: toggle
      localizable: false
      width: 33
      listable: hidden
      instructions_position: above
      visibility: visible
      replicator_preview: true
      hide_display: false
      instructions: 'Define if the team filter is visible.'
  -
    import: theme
  -
    handle: settings_contact_slogan
    field:
      input_type: text
      antlers: false
      type: text
      display: 'Contact slogan'
      icon: text
      localizable: true
      listable: hidden
      instructions_position: above
      visibility: visible
      replicator_preview: true
      hide_display: false
  -
    handle: template
    field:
      hide_partials: true
      blueprint: false
      type: template
      display: Template
      icon: template
      localizable: false
      listable: hidden
      instructions_position: above
      visibility: visible
      replicator_preview: true
      hide_display: false
  -
    handle: layout
    field:
      hide_partials: true
      blueprint: false
      type: template
      display: Layout
      icon: template
      localizable: false
      listable: hidden
      instructions_position: above
      visibility: visible
      replicator_preview: true
      hide_display: false
