tabs:
  main:
    display: Content
    sections:
      -
        display: Content
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              localizable: true
              validate:
                - required
              display: Title
              instructions_position: above
              listable: hidden
              visibility: visible
              replicator_preview: true
              input_type: text
              antlers: false
              hide_display: false
  seo:
    display: SEO
    sections:
      -
        display: SEO
        fields:
          -
            import: seo
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: parent
            field:
              type: entries
              collections:
                - projects
              max_items: 1
              listable: false
              localizable: true
  settings:
    display: Settings
    sections:
      -
        display: Settings
        fields:
          -
            import: settings
title: Project
