tabs:
  main:
    display: Content
    sections:
      -
        display: Content
        fields:
          -
            handle: feature_layout
            field:
              options:
                landscape: Landscape
                portrait: Portrait
              taggable: false
              push_tags: false
              multiple: false
              clearable: false
              searchable: true
              cast_booleans: false
              default: landscape
              type: select
              display: 'Header Layout'
              icon: select
              instructions: 'Choose a layout for the header, depending on the feature image.'
              localizable: false
              listable: hidden
              instructions_position: below
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: title
            field:
              type: text
              required: true
              localizable: true
              validate:
                - required
              display: Title
              instructions_position: above
              listable: hidden
              visibility: visible
              replicator_preview: true
              input_type: text
              antlers: false
              hide_display: false
          -
            handle: client
            field:
              input_type: text
              antlers: false
              type: text
              display: Client
              icon: text
              localizable: true
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: summary
            field:
              buttons:
                - bold
                - unorderedlist
                - removeformat
                - anchor
              smart_typography: false
              save_html: false
              inline: false
              toolbar_mode: fixed
              reading_time: false
              word_count: false
              fullscreen: true
              allow_source: true
              enable_input_rules: true
              enable_paste_rules: true
              remove_empty_nodes: true
              antlers: false
              link_noopener: false
              link_noreferrer: false
              target_blank: false
              always_show_set_button: false
              collapse: false
              previews: true
              type: bard
              display: Summary
              icon: bard
              localizable: true
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: services
            field:
              buttons:
                - bold
                - unorderedlist
                - removeformat
                - anchor
              smart_typography: false
              save_html: false
              inline: false
              toolbar_mode: fixed
              reading_time: false
              word_count: false
              fullscreen: true
              allow_source: true
              enable_input_rules: true
              enable_paste_rules: true
              remove_empty_nodes: true
              antlers: false
              link_noopener: false
              link_noreferrer: false
              target_blank: false
              always_show_set_button: false
              collapse: false
              previews: true
              type: bard
              display: Services
              icon: bard
              localizable: true
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: elements
            field:
              collapse: false
              previews: true
              fullscreen: true
              sets:
                main_elements:
                  display: 'Main Elements'
                  instructions: null
                  icon: addon-boxes-stack
                  sets:
                    fullscreen_image:
                      display: 'Fullscreen Image'
                      instructions: 'Add a fullscreen image'
                      icon: align-object-center
                      fields:
                        -
                          import: image_fullscreen
                    image:
                      display: Image
                      instructions: 'Add an image'
                      icon: media-image-picture-orientation
                      fields:
                        -
                          import: image
                    image_text:
                      display: 'Image - Text'
                      instructions: 'Add an image/text block.'
                      icon: text-formatting-image-left
                      fields:
                        -
                          import: image_text
                graphical_elements:
                  display: 'Graphical Elements'
                  instructions: null
                  icon: addon-boxes-stack
                  sets:
                    horizontal_ruler:
                      display: 'Horizontal Ruler'
                      instructions: null
                      icon: align-object-bottom
                      fields:
                        -
                          import: horizontal_ruler
              type: replicator
              display: Elements
              icon: replicator
              localizable: false
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
  media:
    display: Media
    sections:
      -
        display: Media
        fields:
          -
            handle: feature_image
            field:
              max_files: 1
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: 'Feature image'
              icon: assets
              localizable: false
              listable: hidden
              instructions_position: below
              visibility: visible
              replicator_preview: true
              hide_display: false
              instructions: 'Used on the projects detail page.'
          -
            handle: teaser_image_portrait
            field:
              max_files: 1
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: 'Teaser image: Portrait'
              icon: assets
              instructions: 'Used on the project listing page. Image ratio should be approx. 3:4.'
              localizable: false
              listable: hidden
              instructions_position: below
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: teaser_image_landscape
            field:
              max_files: 1
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: 'Teaser image: Landscape'
              icon: assets
              instructions: 'Used on the project listing page. Image ratio should be approx. 16:8 for fullwidth or 3:2 for landscape mode.'
              localizable: false
              listable: hidden
              instructions_position: below
              visibility: visible
              replicator_preview: true
              hide_display: false
  seo:
    display: SEO
    sections:
      -
        display: SEO
        fields:
          -
            import: seo
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: parent
            field:
              type: entries
              collections:
                - projects
              max_items: 1
              listable: false
              localizable: true
          -
            handle: related
            field:
              mode: select
              create: false
              collections:
                - projects
              type: entries
              display: 'Related projects'
              icon: entries
              localizable: false
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: project_categories
            field:
              type: terms
              taxonomies:
                - project_categories
              display: 'Project Categories'
              mode: select
              localizable: false
          -
            handle: tags
            field:
              type: terms
              taxonomies:
                - tags
              display: Tags
              mode: select
              localizable: false
  settings:
    display: Settings
    sections:
      -
        display: Settings
        fields:
          -
            import: settings
title: Project
