tabs:
  main:
    display: Content
    sections:
      -
        display: Content
        fields:
          -
            handle: feature_layout
            field:
              options:
                landscape: Landscape
                portrait: Portrait
              default: landscape
              type: select
              display: Layout
              instructions: 'Choose a layout for the header, depending on the feature image.'
              localizable: false
              instructions_position: below
              validate:
                - required
          -
            handle: title
            field:
              type: text
              required: true
              localizable: true
              validate:
                - required
              display: Title
          -
            handle: client
            field:
              type: text
              display: Client
              localizable: true
          -
            handle: summary
            field:
              buttons:
                - bold
                - unorderedlist
                - removeformat
                - anchor
              remove_empty_nodes: true
              type: bard
              display: Summary
              localizable: true
          -
            handle: services
            field:
              buttons:
                - bold
                - unorderedlist
                - removeformat
                - anchor
              remove_empty_nodes: true
              type: bard
              display: Services
              localizable: true
          -
            handle: elements
            field:
              collapse: true
              type: replicator
              display: Elements
              localizable: true
              sets:
                main_elements:
                  display: 'Main Elements'
                  icon: addon-boxes-stack
                  sets:
                    fullscreen_image:
                      display: 'Fullscreen Image'
                      instructions: 'Add a fullscreen image'
                      icon: align-object-center
                      fields:
                        -
                          import: image_fullscreen
                    image:
                      display: Image
                      instructions: 'Add an image'
                      icon: media-image-picture-orientation
                      fields:
                        -
                          import: image
                    image_slideshow:
                      display: 'Image Slideshow'
                      icon: media-image-picture-gallery
                      fields:
                        -
                          import: image_slideshow
                    image_comparison:
                      display: 'Image Comparison'
                      icon: media-image-picture-gallery
                      fields:
                        -
                          import: image_comparison
                    image_text:
                      display: 'Image - Text'
                      instructions: 'Add an image/text block.'
                      icon: text-formatting-image-left
                      fields:
                        -
                          import: image_text
                    iframe:
                      display: Iframe
                      icon: programming-script-code-brackets
                      fields:
                        -
                          import: iframe
                    video:
                      display: Video
                      instructions: 'Add a video from file (mp4) or embed code (Youtube, Vimeo)'
                      icon: media-webcam-video
                      fields:
                        -
                          import: video
                    feedbacks:
                      display: Feedbacks
                      instructions: 'Add a set of feedback quotes.'
                      icon: text-formatting-quotation
                      fields:
                        -
                          import: feedbacks
                graphical_elements:
                  display: 'Graphical Elements'
                  icon: addon-boxes-stack
                  sets:
                    horizontal_ruler:
                      display: 'Horizontal Ruler'
                      icon: align-object-bottom
                      fields:
                        -
                          import: horizontal_ruler
  media:
    display: Media
    sections:
      -
        display: Media
        fields:
          -
            handle: feature_type
            field:
              options:
                image: Image
                video: Video
              default: image
              type: select
              display: 'Feature type'
              localizable: false
          -
            handle: feature_image
            field:
              max_files: 1
              container: assets
              type: assets
              display: 'Feature image'
              localizable: false
              instructions_position: below
              instructions: 'Add a feature image used on the projects detail page.'
              if:
                feature_type: 'equals image'
          -
            handle: feature_video
            field:
              max_files: 1
              container: assets
              folder: video
              type: assets
              display: 'Feature video'
              instructions: 'Add a feature video used on the projects detail page. Format needs to be MP4'
              localizable: false
              instructions_position: below
              if:
                feature_type: 'equals video'
          -
            handle: teaser_image_portrait
            field:
              max_files: 1
              container: assets
              type: assets
              display: 'Teaser image: Portrait'
              instructions: 'Used on the project listing page. Image ratio should be approx. 3:4.'
              localizable: false
              instructions_position: below
          -
            handle: teaser_image_landscape
            field:
              max_files: 1
              container: assets
              type: assets
              display: 'Teaser image: Landscape'
              instructions: 'Used on the project listing page. Image ratio should be approx. 16:8 for fullwidth or 3:2 for landscape mode.'
              localizable: false
              instructions_position: below
          -
            handle: teaser_video
            field:
              max_files: 1
              container: assets
              folder: video
              type: assets
              display: 'Teaser video'
              instructions: 'Used on the project listing page.'
              localizable: false
              instructions_position: below
  seo:
    display: SEO
    sections:
      -
        display: SEO
        fields:
          -
            import: seo
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: parent
            field:
              type: entries
              collections:
                - projects
              max_items: 1
              listable: false
              localizable: true
          -
            handle: related
            field:
              mode: select
              create: false
              collections:
                - projects
              type: entries
              display: 'Related projects'
              localizable: false
          -
            handle: project_categories
            field:
              type: terms
              taxonomies:
                - project_categories
              display: 'Project Categories'
              mode: select
              localizable: false
          -
            handle: tags
            field:
              type: terms
              taxonomies:
                - tags
              display: Tags
              mode: select
              localizable: false
  settings:
    display: Settings
    sections:
      -
        display: Settings
        fields:
          -
            import: settings
title: Project
