title: Vermarktung
updated_by: c2f8321e-be41-4d83-b9ee-8136dba46b39
updated_at: 1711445065
blueprint: project_category
localizations:
  en:
    title: Commercialization
    slug: commercialization
    updated_by: c2f8321e-be41-4d83-b9ee-8136dba46b39
    updated_at: 1711445076
