title: Wettbewerb
updated_by: c2f8321e-be41-4d83-b9ee-8136dba46b39
updated_at: 1711444903
blueprint: project_category
localizations:
  en:
    title: Competition
    slug: competition
    updated_by: c2f8321e-be41-4d83-b9ee-8136dba46b39
    updated_at: 1711445023
